version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "comments-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "comment-rest-api"
    environment:
      - DATABASE_USERNAME="postgres"
      - DATABASE_PASSWORD="postgres"
      - DATABASE_DATABASE="postgres"
      - DATABASE_HOST="127.0.0.1"
      - DATABASE_TABLE="postgres"
      - DATABASE_PORT=5432
      - DATABASE_SSL_MODE="disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
